#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 21 18:36:37 2018

@author: johnvdk
"""

# -*- coding: utf-8 -*-
"""
Created on Thu May 17 11:01:22 2018

@author: jerem
"""
import matplotlib.pyplot as plt

Sx = 0.01 #m
St = 0.01 #s
I = 10000 #Iterations
k = 205   #W/m*k
c = 921   #J/kg*C
dens = 2700 #kg/m^3

#Initialize temperature array
T = [50]
for x in range (0,29):
    T.append(20)

#Initialize x coordinates array
Tx = []
for x in range(0,30):
    Tx.append(x*0.01)
    
#Call loop method to see step by step change
def loop():
    for x in range(1,29):
        T[x] = T[x] + (k*St)/(c*dens)*(T[x-1] - 2*T[x] + T[x+1])/(Sx**2)
    plt.plot(Tx[:], T[:], 'ro')
    plt.axis([0, 0.4, 0, 60])
    plt.show()
    input()
    loop()


#Calculate temperatures after set amount of interations
read = False
for time in range(0,I):
    #calculate first
    T[0] = T[0] - k*(T[0] - T[1])/(c*dens*Sx**2)*St
    #calculate last
    T[-1] = T[-1] + k*(T[-2] - T[-1])/(c*dens*Sx**2)*St
    for x in range(1,29):
        T[x] = T[x] + (k*St)/(c*dens)*(T[x-1] - 2*T[x] + T[x+1])/(Sx**2)
        #Checks when 50mm has reached 40 Celsius
        #if T[5] >= 40 and not read:
         #   print(time*St, "seconds")
          #  read = True
        #Checks if third sice reaches 25 Celsius
        if T[2] >= 25 and not read:
            print(time*St, "seconds")
            read = True

#Calculate the mean temperature
sum = 0
for number in T:
    sum = sum + number
mean = sum/len(T)
print(mean, "is the mean temperature")

plt.plot(Tx[:], T[:], 'ro')
plt.axis([0, 0.4, 0, 60])
plt.ylabel('Temperature [C]')
plt.xlabel('Distance [m]')
plt.title('Temperature vs Distance Graph of Aluminum Rod')
plt.show()