#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 24 11:18:31 2018

@author: johnvdk
"""
import matplotlib.pyplot as plt

P0 = 0
T0 = 0
y = 1.4

P1 = P0
Pratio = 40
Tamb = 20 + 273
T3 = 1000 + 273
N = 1 - (1/Pratio)**(1-1/y)
Tratio = (1 - N)
T1 = Tamb
V1 = 1

Pvals = []
V2lst = []
V2=(V1*(1/Pratio)**(1/y))
#Stage 1 - 2

for x in range (1,Pratio + 1):
    Pvals.append(x)
    V2lst.append(V1*(1/x)**(1/y))
    plt.plot(V2lst[:], Pvals[:], 'r')
T2 = T1*(V1/V2)**(y-1)

#Stage 2 - 3
V3 = T3/T2*V2
V3lst = []
P3lst = []
x = V2
while (x < V3):
    P3lst.append(40)
    V3lst.append(x)
    x = x+0.001
    plt.plot(V3lst[:], P3lst[:], 'y')


#Stage 3-4
P4lst = []
V4lst = []
V4 = V3*(Pratio)**(1/y)
T4 = T3*(V4/V3)**(y-1)
for x in range (1,Pratio+1):
    P4lst.append(x)
    V4lst.append(V3*(40/x)**(1/y))
    plt.plot(V4lst[:], P4lst[:], 'g')

V1lst = []
P1lst = []
x = V4
while (x > V1):
    P1lst.append(1)
    V1lst.append(x)
    x = x-0.001
    plt.plot(V1lst[:], P1lst[:], 'b')

plt.show()

